// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/amerihost-logo-concepts/grid/GridContinuity.tsx": () => import("../components/mockups/amerihost-logo-concepts/grid/GridContinuity.tsx"),
  "./components/mockups/amerihost-logo-concepts/monogram/AHMonogram.tsx": () => import("../components/mockups/amerihost-logo-concepts/monogram/AHMonogram.tsx"),
  "./components/mockups/amerihost-logo-concepts/network/NetworkSignal.tsx": () => import("../components/mockups/amerihost-logo-concepts/network/NetworkSignal.tsx"),
  "./components/mockups/amerihost-logo-concepts/wordmark/Wordmark.tsx": () => import("../components/mockups/amerihost-logo-concepts/wordmark/Wordmark.tsx")
};
